version: "2.2"
services:
  n8n:
    container_name: geoffrey-n8n
    build:
      context: n8n
    image: geoffrey/n8n
    restart: always
    env_file: setup.env
    volumes:
      - n8n-volume:/home/node/.n8n
    restart: always
    ports:
      - "5678:5678"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  database:
    container_name: geoffrey-db
    image: mariadb
    env_file: setup.env
    volumes:
      - mariadb-volume:/var/lib/mysql
      - ./mariadb-setup:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cache:
    container_name: geoffrey-cache
    image: redis:6
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  directus:
    container_name: geoffrey-directus
    build:
      context: directus
    image: geoffrey/directus
    restart: always       
    ports:
      - 8055:8055
    depends_on:
      - cache
      - database
    environment:
      KEY: '7e506fd4-402b-4566-8dbd-8cc822b694dc'
      SECRET: 'b4a3e042-88db-49b3-b433-bd42b5d48522'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'geoffrey'
      DB_USER: 'directus_uzr'
      DB_PASSWORD: 'bd42b5d48522'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'        
  
volumes:
  n8n-volume:
  mariadb-volume:
