version: "2.2"
services:
  n8n:
    container_name: geoffrey-n8n
    build:
      context: n8n
    image: geoffrey/n8n
    restart: always
    env_file: setup.env
    volumes:
      - n8n-volume:/home/node/.n8n
    restart: always
    ports:
      - "5678:5678"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  database:
    container_name: geoffrey-db
    image: mariadb
    env_file: setup.env
    volumes:
      - mariadb-volume:/var/lib/mysql
      - ./mariadb-setup:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cache:
    container_name: geoffrey-cache
    image: redis:6
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  directus:
    container_name: geoffrey-directus
    build:
      context: directus
    image: geoffrey/directus
    restart: always       
    ports:
      - 8055:8055
    depends_on:
      - cache
      - database
    env_file: setup.env
  
  metabase:
    container_name: geoffrey-metabase
    build:
      context: metabase
    image: geoffrey/metabase
    restart: always       
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file: setup.env

volumes:
  n8n-volume:
  mariadb-volume:
